name: outrigger-env
channels:
  - conda-forge
  - r
  - bioconda
dependencies:
- python=3.6.7
- pytest
- pandas>=0.17.0
- coverage
- gffutils
- pybedtools
- biopython
- bedtools
- joblib
- pysam
- sphinx>=1.3.6
- sphinx_rtd_theme
- outrigger
- pip:
    - graphlite
    - recommonmark==0.4.0
    - nbsphinx
